CREATE TABLE Major
( mjr_id INT  PRIMARY KEY AUTO INCREMENT,
 mjr_name NVARCHAR(20) NOT NULL)

 CREATE TABLE ProblemType
 (plt_id INT PRIMARY KEY AUTO INCREMENT,
 pl_type NVARCHAR(10) NOT NULL)

 CREATE TABLE Teacher
 (tch_id INT PRIMARY KEY AUTO INCREMENT,
 u_id INT NOT NULL CONSTRAINT u_id FOREIGN KEY REFERENCES Admission(u_id),
 tch_name NVARCHAR(10) NOT NULL
 )
 CREATE TABLE Problem
 (pl_id INT PRIMARY KEY AUTO INCREMENT,
 tch_id INT NOT NULL CONSTRAINT tch_id FOREIGN KEY REFERENCES Teacher(tch_id),
 plt_id INT NOT NULL CONSTRAINT plt_id FOREIGN KEY REFERENCES Problemtype(plt_id),
 pl_name NVARCHAR(20) NOT NULL,
 pl_degree NVARCHAR(10) NOT NULL,
 pl_need TEXT NOT NULL,
 pl_eva_mode TEXT NOT NULL,
 max_person INT NOT NULL)

 CREATE TABLE ProblemProfession
 (pl_id INT NOT NULL CONSTRAINT pl_id FOREIGN KEY REFERENCES Problem(pl_id),
 mjr_id INT NOT NULL CONSTRAINT mjr_id FOREIGN KEY REFERENCES Major(mjr_id),
 CONSTRAINT PP_key PRIMARY KEY(pl_id,mjr_id))
